name: some handmade examples
on: push

jobs:
  ifBranch:
    if: github.ref == 'refs/branch/develop'
    name: See branch and do jobs
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: echo
        run: echo "this branch is develop"

  ifBranchMatrix:
    strategy:
      matrix:
        branch: ["refs/branch/develop", "refs/branch/staing"]
    if: github.ref ==  ${{ matrix.branch }}
    name: See branch and do jobs
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: echo
        run: echo "this branch is develop"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 12.x
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
